import requests
import wikipediaapi
from time import sleep
from collections import deque
from bs4 import BeautifulSoup
                                                  
#setup

wiki = wikipediaapi.Wikipedia(user_agent = "EVILWEBSCRAPER (hiimweasel123@gmail.com)", language = "en",
                              extract_format = wikipediaapi.ExtractFormat.WIKI)

url = "https://en.wikipedia.org/wiki/Web_scraping" #url to scrape
headers = {
    "User-Agent": "WikiBridge/1.0 (hiimweasel123@gmail.com)" #less likely to be blocked
}



cache = {} #cache for already searched articles

def get_title(query): #get title
    page = wiki.page(query)
    if not page.exists():
        print("EXPLODED")
    return page.title

def get_related_articles(title):
    if title in cache: #return related articles from cache if its there
        return cache[title]
    
    title_underscore = title.replace(" ", "_") #turn title into url
    url = f"https://en.wikipedia.org/wiki/{title_underscore}"

    page = requests.get(url, headers=headers)
    soup = BeautifulSoup(page.content, "html.parser") #parse page to make readable
    body = soup.find(id = "bodyContent")

    references = body.find(id = "References") 

    if references:
        

        heading_block = references.find_parent(class_ = "mw-heading") or references.parent

        for el in list(heading_block.find_all_next()): #remove everything after references
            el.extract()

        heading_block.extract()

    related_articles = soup.find(id = "bodyContent").find_all("a") #find all links

    if related_articles is None:
        raise RuntimeError(f"couldn't find related articles for {title}")


    scrape_links = []

    useless = ("File:", "Help:", "Category:", "Wikipedia:", "Template:",
            "Portal:", "Special:", "Talk:") #list of useless junk to filter out def not generated by claude

    for link in related_articles: 
        href = link.get("href")

        if not href or not href.startswith("/wiki"): #if no href, continue
            continue
        
        name = href[6:]
        
        if name.split(":")[0] + ":" in useless: #filter out useless
            continue
        
        name = href[len("/wiki/"):] 
        scrape_links.append(name.replace("_", " "))

    cache[title] = scrape_links #add to cache
    return scrape_links 


def bi_bfs(start, target, depth):
    start = get_title(start)
    target = get_title(target)


    parents1 = {start: None} #parents of nodes
    parents2 = {target: None}

    frontier1 = deque([start]) #frontier of nodes to search
    frontier2 = deque([target])

    


    def expand(layer, visited, other_visited): #expand one layer
        if not isinstance(layer, deque): 
            raise RuntimeError("somehow layer is not a deque")
        
        collisions = [] #where the two sides meet
        for i in range(len(layer)): #length of the layer added last iteration
            el = layer.popleft()
            for node in get_related_articles(el): #each node is a related article
                print(node)
                if node in other_visited: #if collision

                    print("PARENTS OF COLLISION:", el, other_visited[node])
                    collisions.append(node)
                    visited[node] = el
                elif node not in visited: #if node hasn't been visited yet
                    visited[node] = el
                    layer.append(node)
                
        return collisions
        
    def reconstruct_path(collision_node, side1, side2):
        print("collision:", collision_node) 
        x1 = side1[collision_node] 
        path1 = [x1]
        while x1 != None: #reconstruct one side using parents
            print(x1)
            x1 = side1[x1]

            if x1 == None:
                break

            path1.append(x1)
        x2 = side2[collision_node] #reconstructs other side using parents
        path2 = [x2]
        while x2 != None:
            print(x2)
            x2 = side2[x2]

            if x2 == None:
                break
            
            path2.append(x2)

        path1.reverse()
        path = path1 + [collision_node] + path2 #combines path and collision
        return path

    print("test1")

    for i in range(depth):
        result1 = (expand(frontier1, parents1, parents2)) #expand both sides by 1
        result2 = (expand(frontier2, parents2, parents1))

        if result1 != []: #checking if collided
            result1_paths = []
            for el in result1:
                result1_paths.append(reconstruct_path(el, parents1, parents2))
            return result1_paths

        elif result2 != []: #checking if collided
            result2_paths = []
            for el in result2:
                result2_paths.append(reconstruct_path(el, parents1, parents2))
            return result2_paths

    
        
        


    



print(bi_bfs("Pizza", "Moon_landing", 2))


