import requests
from bs4 import BeautifulSoup
                                                  

url = "https://en.wikipedia.org/wiki/Web_scraping" #url to scrape
headers = {
    "User-Agent": "WikiBridge/1.0 (hiimweasel123@gmail.com)" #less likely to be blocked
}

page = requests.get(url, headers = headers) #scrape page

soup = BeautifulSoup(page.content, "html.parser") #parse page to make readable
title = soup.find(id = "firstHeading") #get title of article

related_articles = soup.find(id = "bodyContent").find_all("a") #find all links

if related_articles is None:
    print("EXPLODE")

scrape_links = []

useless = ("File:", "Help:", "Category:", "Wikipedia:", "Template:",
        "Portal:", "Special:", "Talk:") #list of useless junk to filter out def not generated by claude

for link in related_articles: 
    href = link.get("href")

    if not href or not href.startswith("/wiki"): #if no href, continue
        continue
    
    name = href[6:]
    
    if name.split(":")[0] + ":" in useless: #filter out useless
        continue

    scrape_links.append(link.getText())

    


print(soup.prettify())
print()
print(title.getText())
print()
print(scrape_links)